### SERVER SIDE ONLY SETTINGS
dbConnStr:
    # admin connection should grant full data modification rights
    admin: "pgsql: user=repo"
    # guest connection should be read-only
    guest: "pgsql: user=guest"
storage: 
    dir: /home/repo/data
    tmpDir: /home/repo/tmp
    # number of binary resources directory storage levels
    # each level corresponds to a two-digit part of the resource id counting from right, e.g.:
    # - id = 1234567 and level = 1 stores a binary in  {dir}/67/1234567
    # - id = 1234567 and level = 2 stores a binary in  {dir}/67/45/1234567
    # - id = 9 and level = 2 store a binary in {dir}/09/00
    levels: 2
    modeDir: 770
    modeFile: 660
    # as accepted by the https://www.php.net/manual/en/function.hash-init.php
    hashAlgorithm: sha1
accessControl:
    adminRoles:
        - admin
    create:
        # who can create new resources
        allowedRoles:
            - creator
        # rights assigned to the creator uppon resource creation
        creatorRights:
            - read
            - write
        # rights assigned to other roles upon resource creation
        assignRoles:
            read: []
    defaultAction:
        read: deny
        write: deny
    enforceOnMetadata: false
    schema:
        read: https://vocabs.acdh.oeaw.ac.at/schema#acl
        write: https://vocabs.acdh.oeaw.ac.at/schema#aclWrite
    db:
        connStr: 'pgsql: '
        table: users
        userCol: user_id
        dataCol: data
    authMethods:
        - class: \zozlak\auth\authMethod\TrustedHeader
          parameters:
            - HTTP_EPPN
        - class: \zozlak\auth\authMethod\HttpBasic
          parameters:
            - repo
        - class: \zozlak\auth\authMethod\Guest
          parameters:
            - public
metadataManagment:
    nonRelationProperties:
        - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    autoAddIds:
        # add/skip/deny
        default: add
        addNamespaces: []
        skipNamespaces: []
        denyNamespaces: []
transactionController:
    socket: 
        # unix/inet
        type: unix
        # only for the unix type
        path: /home/repo/txSocket
        # only for the inet type
        address: ''
        # only for the inet type
        port: 0
    logging:
        file: /home/repo/logs/txlog
        # debug/info/notice/warning/error/critical/alert/emergency
        level: info
    # transaction state check interval in ms
    checkInterval: 200
    # transaction timeout in s
    timeout: 5
    # do transactions have to be complete in ACID terms?
    enforceCompleteness: false
    # should metadata history table contain only one set of entries per transaction?
    simplifyMetaHistory: true
fullTextSearch:
    # e.g. "java -Xmx1g -jar ../tika-app.jar --text" or "http://127.0.0.1:12345/"
    tikaLocation: http://127.0.0.1:12345/
    sizeLimits:
        indexing: 1G
        highlighting: 10M
    mimeFilter:
        # skip/include
       type: include
       mime:
           - text/html
           - text/plain
           - text/turtle
           - text/xml
           - application/xml
           - application/pdf
    propertyFilter:
        type: skip
        properties:
            - https://vocabs.acdh.oeaw.ac.at/schema#acl
# Handler module for basic metadata triples management
# Must be activated in particular rest->handlers->methods
metadataManager:
    # triples to be always added
    fixed: []
        # http://sample/resource: 
        #     - uri: http://www.w3.org/ns/ldp#NonRDFSource
        # http://sample/literal:
        #     - value: sample value
        #       type: https://sample/type
        #       lang: en
    # triples to be added when a given property is missing
    default:
        https://vocabs.acdh.oeaw.ac.at/schema#acl:
            - value: public
    forbidden: []
    copying: []
        # 'https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize': https://my.own/size/property
rest:
    logging:
        file: /home/repo/logs/repo
        # debug/info/notice/warning/error/critical/alert/emergency
        level: info
    defaultMime: application/octet-stream
    defaultMetadataFormat: text/turtle
    metadataFormats:
        - text/turtle
        - application/json
        - application/ld+json
        - application/n-triples
        - application/rdf+xml
    # resource/neighbors/relatives
    defaultMetadataReadMode: neighbors
    # add/merge/overwrite (merge is probably the only sane default)
    defaultMetadataWriteMode: merge
    # resource/neighbors/relatives
    defaultMetadataSearchMode: resource
    handlers:
        rabbitMq:
            #host: localhost
            #port: 5672
            #user: guest
            #password: guest
            ## in s
            #timeout: 1
            #exceptionOnTimeout: true
        classLoader:
            #acdhOeaw\acdhRepo\tests: /home/zozlak/roboty/ACDH/repo/rdbms/tests
        methods:
            get:
            create:
                - type: function
                  function: \acdhOeaw\acdhRepo\handler\MetadataManager::manage
                #- type: rpc
                #  queue: onCreateRpc
            delete:
            updateBinary:
                - type: function
                  function: \acdhOeaw\acdhRepo\handler\MetadataManager::manage
            updateMetadata:
                - type: function
                  function: \acdhOeaw\acdhRepo\handler\MetadataManager::manage
            txBegin:
            txCommit:
                #- type: function
                #  function: \acdhOeaw\acdhRepo\tests\Handler::onCommit
            txRollback:
### BOTH SERVER AND CLIENT SIDE CONFIG
    urlBase: https://acdhrepo.localhost
    pathBase: /rest/
    headers:
        metadataReadMode: X-METADATA-READ-MODE
        metadataParentProperty: X-PARENT-PROPERTY
        metadataWriteMode: X-METADATA-WRITE-MODE
        transactionId: X-TRANSACTION-ID
schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
    delete: delete://delete
    searchMatch: search://match
    searchFts: search://fts
    binarySize: https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize
    fileName: http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#filename
    mime: https://vocabs.acdh.oeaw.ac.at/schema#hasFormat
    hash: http://www.loc.gov/premis/rdf/v1#hasMessageDigest
    modificationDate: http://fedora.info/definitions/v4/repository#lastModified
    modificationUser: http://fedora.info/definitions/v4/repository#lastModifiedBy
    binaryModificationDate: http://binModDate
    binaryModificationUser: http://binModUser
    creationDate: http://fedora.info/definitions/v4/repository#created
    creationUser: http://fedora.info/definitions/v4/repository#createdBy
